In [27]:
import math

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns

In [2]:
import sys
sys.path.append("../") # go to parent dir

#### Exercise 1

(a) $E[Y_i | X_i] = \beta_0 + \beta_1 X_i + E[\epsilon_i|X_i] = \beta_0 + \beta_1 X_i$

In [4]:
beta0 = 1.4
beta1 = 1.7
X1 = 1
sigma = np.sqrt(0.3)

In [5]:
beta0 + beta1 * X1

3.0999999999999996

$\mathrm{Var}[Y_i | X_i] = \mathrm{Var}[\beta_0 + \beta_1 X_i + \epsilon_i | X_i] = \mathrm{Var}[\epsilon_i|X_i] = \mathrm{Var}[\epsilon_i]$

In [6]:
sigma ** 2

0.29999999999999993

$P(Y_i \leq 3 | X_i = 1) = P(\beta_0 + \beta_1 X_i + \epsilon_i \leq 3 | X_i = 1) = P(\epsilon_i \leq -0.1) = \Phi\left(\frac{-0.1}{\sigma}\right)$

In [8]:
stats.norm.cdf(-0.1 / sigma)

0.42756607029235294

(b) If $X_i \sim N(1, 0.7)$, then $Y_i \sim N(\beta_0 + \beta_1 E[X_i] + E[\epsilon_i], \beta_1^2 \mathrm{Var}[X_i] + \mathrm{Var}[\epsilon_i])$

The expected value of $Y_i$ is:

In [10]:
beta0 + beta1 * 1

3.0999999999999996

The variance of $Y_i$ is:

In [11]:
beta1 ** 2 * 0.7 + 0.3

2.3229999999999995

#### Exercise 2

Assuming a linear model $Y_i = \beta_0 + \beta_1 X_i + \epsilon_i$, we have $\epsilon_i = Y_i - \beta_0 - \beta_1 X_i$. If $\epsilon_i$ are i.i.d. $N(0,\sigma_\epsilon^2)$, then the likelihood is
$$L(\beta_0,\beta_1) = \prod_{i=1}^n \frac{1}{\sqrt{2\pi} \sigma} \exp\left(-\frac{\epsilon_i^2}{2\sigma^2}\right),$$
and the log-likelihood is given by
$$\log L(\beta_0,\beta_1) = -\frac{n}{2} \log(2 \pi) - n \log \sigma_\epsilon - \sum_{i=1}^n \frac{\epsilon_i^2}{2\sigma^2} = -\frac{n}{2} \log(2 \pi) - n \log \sigma_\epsilon - \sum_{i=1}^n \frac{(Y_i - \beta_0 - \beta_1 X_i)^2}{2\sigma^2}.$$
Setting
$$\frac{d}{d\beta_0} \log L(\beta_0, \beta_1) = 0$$
and
$$\frac{d}{d\beta_1} \log L(\beta_0, \beta_1) = 0$$
leads to the following equations:
$$\frac{d}{d\beta_0} \sum_{i=1}^n (Y_i - \beta_0 - \beta_1 X_i)^2 = 0,$$
$$\frac{d}{d\beta_1} \sum_{i=1}^n (Y_i - \beta_0 - \beta_1 X_i)^2 = 0,$$
which are the least-squares equations for $\beta_0$ and $\beta_1$, and hence have the same solutions.

#### Exercise 3

$$\mathrm{Var}[\hat{\beta}_1|X_1, ..., X_n] 
= \mathrm{Var}\left[\sum_{i=1}^n w_i Y_i|X_1, ..., X_n\right] 
= \mathrm{Var}\left[\sum_{i=1}^n w_i (\beta_0 + \beta_1 X_i + \epsilon_i)|X_1, ..., X_n\right] 
= \mathrm{Var}\left[\sum_{i=1}^n w_i \epsilon_i\right] 
= \sum_{i=1}^n w_i^2 \mathrm{Var}[\epsilon_i]
= \sigma_\epsilon^2 \sum_{i=1}^n w_i^2 = \\
= \sigma_\epsilon^2 \sum_{i=1}^n \frac{(X_i - \bar{X})^2}{\left( \sum_{j=1}^n (X_j - \bar{X})^2 \right)^2}
= \sigma_\epsilon^2 \frac{\sum_{i=1}^n (X_i - \bar{X})^2}{\left( \sum_{j=1}^n (X_j - \bar{X})^2 \right)^2}
= \frac{\sigma_\epsilon^2}{\sum_{j=1}^n (X_j - \bar{X})^2}
= \frac{\sigma_\epsilon^2}{(n - 1) s_X^2}.$$

#### Exercise 4

In [16]:
Xi = np.arange(30) * 14 / (30 - 1) + 1

(a) The correlation coefficient between $X$ and $X^2$:

In [19]:
np.corrcoef(Xi, Xi ** 2)[0, 1]

0.9738711056686896

In [28]:
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [29]:
def vif(x):
    x = sm.add_constant(x, prepend=True)
    return pd.Series([variance_inflation_factor(x, i) for i in range(len(x.columns)) if x.columns[i] != 'const'], index=x.columns[1:])

The VIFs are:

In [30]:
vif(pd.DataFrame({'X': Xi, 'X^2': Xi ** 2}))

X      19.389213
X^2    19.389213
dtype: float64

Therefore, $X$ and $X^2$ are highly collinear.

(b) The correlation coefficients between $X - \bar{X}$ and $(X - \bar{X})^2$:

In [32]:
np.corrcoef(Xi - np.mean(Xi), (Xi - np.mean(Xi)) ** 2)[0, 1]

0.0

and the VIFs are:

In [33]:
vif(pd.DataFrame({'X': Xi - np.mean(Xi), 'X^2': (Xi - np.mean(Xi)) ** 2}))

X      1.0
X^2    1.0
dtype: float64

Therefore $(X-\bar{X})$ and $(X-\bar{X})^2$ are not collinear.

#### Exercise 5

Given $\rho(Y, \hat{Y}) = 0.65$ and $\mathrm{TSS}=100$:

(a) $R^2 = \rho(Y, \hat{Y}) ^2 = 0.65^2$.

(b) $\mathrm{reg. SS} = \mathrm{TSS} ( 1- R^2) = 35.$

(c) $\mathrm{res. SS} = \mathrm{TSS} \cdot R^2 = 65.$

(d) $s^2 = \frac{\mathrm{res. SS}}{n - p - 1} = \frac{65}{96}.$

#### Exercise 6

$C_p = \frac{SSE(p)}{\hat{\sigma}_{\epsilon, M}^2} - n + 2 (p + 1)$

In [49]:
def Cp(SSE, sigma, n, p):
    return SSE / sigma ** 2 - n + 2 * (p + 1)
def Rsq(SSE, TSS):
    return 1 - SSE / TSS

In [43]:
RSS = np.array([12.2, 10.1, 10.0])
p = np.array([3, 4, 5])

In [50]:
n = 66
sigma_eps = np.sqrt(RSS[2] / (n - p[2] - 1))
TSS = 48

In [51]:
Cp(RSS, sigma_eps, n, p) 

array([15.2,  4.6,  6. ])

In [52]:
Rsq(RSS, TSS)

array([0.74583333, 0.78958333, 0.79166667])

Based on this information, one should pick the model with 4 parameters. $R^2$ should not be used to compare models - instead, one could use the adjusted $R^2$.

#### Exercise 7

Within the setup of the regression problem (i.e. assuming the true model is $Y_i = \beta_0 + \beta_1 X_i + \beta_2 X_i^2 + \epsilon_i$), the result does not allow us to reject the hypothesis that both $\beta_1$ and $\beta_2$ are zero.

However, this does not provide evidence on the validity of the chosen model as such.

#### Exercise 8

Setting
$$\frac{d}{d\beta_1} \sum_{i=1}^n (Y_i - \beta_1 X_i)^2 = 0$$
gives us
$$\beta_1 = \frac{\sum_{i=1}^n X_i Y_i}{\sum_{i=1}^n X_i^2}.$$

#### Exercise 9

| Source     | df  | SS    | MS    | F    | P    |
| ---        | --- | ---   | ---   | ---  | ---  |
| Regression | 2   | 5.851 | 2.926 | 4.26 | 0.04 |
| Error      | 12  | 5.66  | 0.472 |
| Total      | 15  |

MS = SS / error df:

In [68]:
MS = 5.66 / 12
MS

0.4716666666666667

The F statistic can be recovered from the p-value:

In [67]:
F = stats.f.ppf(1 - 0.04, 2, 12)
F

4.259855680060178

$\sigma_\epsilon = \sqrt{\text{error MS}}$:

In [69]:
sigma = np.sqrt(MS)
sigma

0.6867799259345505

Then regression MS is F * $\sigma_\epsilon$:

In [71]:
regMS = F * sigma
regMS

2.9255833684436032

and regression SS is regression MS * regression df:

In [72]:
regMS * 2

5.8511667368872065

#### Exercise 10

(a) 1.042

(b) 0.93492

(c) The 95% confidence interval is:

In [75]:
np.array([-1, 1]) * 1.96 * 0.01209 + 0.152

array([0.1283036, 0.1756964])

(d) The convergence code 0 mean successful completion.